version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: booking-postgres
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: booking_db_pass_word
    ports:
      - "5432:5432"